### ISSUE TITLE
Emoticons in the graffiti are not rendered when running as Docker container

### ISSUE THREAD

**Issue by fab-10** [Consensys-Incorporated/teku#5731]
### Description

When Teku runs as a Docker container, emoticons in the graffiti are not rendered.

### Steps to Reproduce (Bug)

Run Teku via the following docker compose file

```
version: '3.6'

services:
  teku:
    image: "consensys/teku:22.5.2"
    user: "1001"
    container_name: "teku"
    restart: always
    volumes: ['/data/teku:/data', '/etc/teku:/config', '/var/log/teku:/log']
    ports: ['9000:9000']
    command: --data-base-path=/data --validators-graffiti="Besu 🐐 Teku" --network=ropsten --validator-keys=/config/keys:/config/secrets --ee-endpoint=http://10.0.0.1:8551 --ee-jwt-secret-file=/config/jwt-secret.hex --eth1-endpoint=http://10.0.0.1:8545 --validators-proposer-default-fee-recipient=0x... --logging=info --Xnetwork-total-terminal-difficulty-override=50000000000000000
```

wait for a block and check the graffiti, on Beaconcha.in it is rendered as `Besu ���� Teku` instead of `Besu 🐐 Teku`

**Expected behavior:** [What you expect to happen]

See the emoticons in the produced block

**Actual behavior:** [What actually happens]

invalid chars are rendered in place of emoticons

**Frequency:** [How regularly does it occur?]

always when running in Docker

### Versions (Add all that apply)
* Software version: 22.5.2
* OS Name & Version: Amazon Linux 2
* Docker Version: 20.10.13
* Cloud VM, type, size: AWS
