### ISSUE TITLE
Teku validator getting invalid response from Beacon Node API while connected to nimbus beacon client

### ISSUE THREAD

**Issue by TobiWo** [Consensys-Incorporated/teku#5845]
### Description
I have the following docker-compose setup:

1. teku beacon node
1. teku validator instance with two validators connected to the teku beacon client
1. nimbus beacon client with also two validators on it's own

This is running on the Prater testnet.

I just wanted to test different client combinations and realized the following while I switched the **teku validator to the nimbus beacon client**:
1. The logs indicate that the validator connects to the nimbus beacon client event stream
1. However, no attestations are published which results in missing attestations

I also tried to connect teku to nimbus while nimbus is not running own validators but the result was the same.

Please find attached the log files for the teku validator (TRACE mode) and an example log from the nimbus beacon client (DEBUG mode).

### Steps to Reproduce (Bug)
These are the docker-compose configs:

Note: I discard the teku beacon node config here (as described above) as this does not add any relevant information for the issue. 

#### teku compose
```yaml
version: '3.8'
services:

  teku-validator-prater:
    image: consensys/teku:22.6.0
    container_name: teku-validator-prater
    command:
      - validator-client
      - --data-path
      - "/consensus_data"
      - --network
      - "prater"
      - --metrics-enabled
      - --beacon-node-api-endpoint
      - "http://10.3.0.5:5052"
      - --validator-keys
      - "/consensus_data/validator/keys:/consensus_data/validator/passwords"
      - --validators-graffiti
      - "TobiWo"
    volumes:
      - /mnt/teku_prater/consensus_data:/consensus_data
    stop_grace_period: 2m
    restart: always
    networks:
      goerli-prater:
        ipv4_address: 10.3.0.7

networks:
  goerli-prater:
    external: true
```

#### nimbus compose
```yaml
version: '3.8'
services:

  nimbus-prater:
    image: statusim/nimbus-eth2:amd64-v22.6.0
    container_name: nimbus-prater
    command:
      - --data-dir=/consensus_data
      - --network=prater
      - --metrics
      - --rest
      - --rest-address=0.0.0.0
      - --rest-allow-origin=*
      - --web3-url=ws://10.3.0.2:8546
      - --validator-monitor-auto
    stop_grace_period: 2m
    volumes:
      - /mnt/nimbus_prater/consensus_data_nimbus:/consensus_data
    restart: always
    networks:
      goerli-prater:
        ipv4_address: 10.3.0.5

networks:
  goerli-prater:
    external: true
```

Just for your reference, the docker network is defined in a different yaml.

**Expected behavior:**
1. Teku connects to nimbus successfully
1. Attestations are published successfully

**Actual behavior:**
See description and logs.

**Frequency:**
It occurs everytime I connect the teku validator to the nimbus beacon client.

### Versions
* teku version: v22.6.0
* nimbus image (version): nimbus-eth2:amd64-v22.6.0
* Docker Version: 20.10.16
* Cloud VM, type, size: 8 vCPUs, 32GB RAM, 500GB SSD storage, Ubuntu 20.04 (updated)

### Logs
[teku_validator_to_nimbus_beacon_stacktrace.log](https://github.com/ConsenSys/teku/files/8985556/teku_validator_to_nimbus_beacon_stacktrace.log)
[nimbus_error_responce.log](https://github.com/ConsenSys/teku/files/8985559/nimbus_error_responce_for_teku_validator.txt)
