### ISSUE TITLE
edge case handling gossip on the transition boundary

### ISSUE THREAD

**Issue by rolfyone** [Consensys-Incorporated/teku#6499]
It looks like we're rejecting a gossip message on fork boundary because we're using the pre-state fork...

This was reported during a devnet. The devnet was similar to mainnet config, so 32 blocks per epoch. 

> right after bellatrix: 
> ```
> 2022-11-23 10:27:05.288 WARN  - Rejecting gossip message on topic /eth2/66ebd40c/sync_committee_contribution_and_proof/ssz_snappy, reason: Rejecting proof with signature 0x93ab576659aa724daef79cc8b0ce3d740b224c2d8e84b97efdbd7184b12fbb023e8303b83a1dbcf1f2df740814af52150d5564f288dca312ae247a7fc2ee423c3778ce20b3526e003ee915da34857a9ebe53b7595c25f1cce5e71d9d09befd27 because batch signature check failed, decoded message: 0x4600000000000000400000000000000017a0d9ddd3711fcba220197f21557dbb1e58e6c8a257dd14027491d6acea6c0801000000000000000121409410483c00108001210014104893ab576659aa724daef79cc8b0ce3d740b224c2d8e84b97efdbd7184b12fbb023e8303b83a1dbcf1f2df740814af52150d5564f288dca312ae247a7fc2ee423c3778ce20b3526e003ee915da34857a9ebe53b7595c25f1cce5e71d9d09befd27a77c2d0f61acd1aeac35ca71e876ec688d59d0f485e786e287b99c6fe3a972f2cd125d8d233d6c6bc16e45ef7e75662815cc063e713c3fe910d5026f411e764c2075e38350e50464639536eb325aae4c92c2f92fe7077bf84d1e665bc497e44c92cbf341e1d55fe41663c3c680d7aac9709205d6d9003d04f57f7e907a0794989accfd8aa7b8c6de2800e36bfbe06d0c12aac385a8ca1e89fe8c576086e71582bdb74766b9a5f4761ebb898b5f4613276080675c4872630eda84a8e61a470b0a
> ```

decoded gossip message was:
```
message:
  aggregator_index: '70'
  contribution:
    slot: '64'
    beacon_block_root: '0x17a0d9ddd3711fcba220197f21557dbb1e58e6c8a257dd14027491d6acea6c08'
    subcommittee_index: '1'
    aggregation_bits: '0x0121409410483c001080012100141048'
    signature: >-
      0x93ab576659aa724daef79cc8b0ce3d740b224c2d8e84b97efdbd7184b12fbb023e8303b83a1dbcf1f2df740814af52150d5564f288dca312ae247a7fc2ee423c3778ce20b3526e003ee915da34857a9ebe53b7595c25f1cce5e71d9d09befd27
  selection_proof: >-
    0xa77c2d0f61acd1aeac35ca71e876ec688d59d0f485e786e287b99c6fe3a972f2cd125d8d233d6c6bc16e45ef7e75662815cc063e713c3fe910d5026f411e764c2075e38350e50464639536eb325aae4c92c2f92fe7077bf84d1e665bc497e44c
signature: >-
  0x92cbf341e1d55fe41663c3c680d7aac9709205d6d9003d04f57f7e907a0794989accfd8aa7b8c6de2800e36bfbe06d0c12aac385a8ca1e89fe8c576086e71582bdb74766b9a5f4761ebb898b5f4613276080675c4872630eda84a8e61a470b0a

```
