### ISSUE TITLE
[v22.12.0] /eth/v1/remotekeys BadMessageException: 400: Invalid SNI

### ISSUE THREAD

**Issue by ThomasDalla** [Consensys-Incorporated/teku#6564]
Since upgrading to `v22.12.0`, the `/eth/v1/remotekeys` endpoint on the Validator REST API does not work anymore.

## Config

```yaml
# Validators API
validator-api-port: 5062
validator-api-enabled: true
validator-api-docs-enabled: true
validator-api-interface: "0.0.0.0"
validator-api-keystore-file: "/validator/store/validator_store.p12"
validator-api-keystore-password-file: "/validator/store/validator_store.txt"
validator-api-host-allowlist: ["127.0.0.1", ...]
```
## Command

`$ curl -s --insecure -H "Authorization: Bearer x-y-z" -H "Accept: application/json" https://127.0.0.1:5062/eth/v1/remotekeys | jq`

Have also tested different IPs and hostnames (all allowed in the `validator-api-host-allowlist`), same result (works with `22.11`, SNI error with `22.12`.
* 127.0.0.1
* localhost
* hostname
* hostname.xyz

## 22.11.0-jdk17-amd64

```json
{
  "data": [
    {
      "pubkey": "0xABC",
      "url": "http://172.31.0.90:9000",
      "readonly": true
    },
    {
      "pubkey": "0xDEF",
      "url": "http://172.31.0.90:9000",
      "readonly": true
    }
  ]
}
```

## 22.12.0-jdk17-amd64

```json
{
  "cause0": "org.eclipse.jetty.http.BadMessageException: 400: Invalid SNI",
  "message": "Invalid SNI",
  "url": "/eth/v1/remotekeys",
  "status": "400"
}
```
