### ISSUE TITLE
liveness endpoint does not conform to the specification

### ISSUE THREAD

**Issue by arnetheduck** [Consensys-Incorporated/teku#7498]
https://github.com/ethereum/beacon-APIs/blob/205bb822e920fcbbf6db0ffa021b83c505299490/apis/validator/liveness.yaml#L39

```
            title: PostLivenessResponseBody
            type: object
            properties:
              data:
                type: array
                items:
                  type: object
                  properties:
                    index:
                      $ref: '../../beacon-node-oapi.yaml#/components/schemas/Uint64'
                    is_live:
                      type: boolean
```

Teku seems to throw in in an extra `epoch` field which is not part of the standard.
